# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
cache: packages

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get update -qq
  - sudo apt-get install libproj-dev libudunits2-dev libgdal20 gdal-bin libgdal-dev

r_build_args: --resave-data=best

notifications:
  email:
    on_success: change
    on_failure: change
