language: c++
cache: packages
os:
  - linux

dist: trusty
sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo 'deb http://cran.rstudio.com/bin/linux/ubuntu trusty/' | sudo tee --append /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libgdal-dev libproj-dev r-base r-base-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo Rscript -e "install.packages('devtools',repos='http://cran.us.r-project.org')"; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo Rscript -e "devtools::install_github('e-sensing/sits')"; fi

